name: Update News Information

on:
  workflow_dispatch:
  schedule:
    #- cron: '*/10 * * * *'
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - name: set up python 3
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          
      - name: prepare release
        uses: actions/checkout@v3
        with: 
          ref: main

      #- name: Cache pip
      #  uses: actions/cache@v3
      #  with:
      #    path: ~/.cache/pip
      #    key: ${{ runner.os }}-pip-${{ hashFiles('getnews/requirements.txt') }}
      #    restore-keys: |
      #      ${{ runner.os }}-pip-
          
      - name: install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: set variables
        run: |
          echo "UPDATE_TIME=$(TZ='Asia/Jakarta' date +%Y-%m-%d\ %H:%M)" >> $GITHUB_ENV
      
      - name: send webhook
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          UPDATE_TIME: ${{ env.UPDATE_TIME }}
        run: |
          python3 main.py
      
      - name: push release
        run: |
          git config --local user.name github-actions
          git config --local user.email github-actions@github.com
          git add data.json
          git commit -m "auto update at ${{ env.UPDATE_TIME }}" --allow-empty
          git push
